CREATE TABLE IF NOT EXISTS work_permits (
  permit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_code VARCHAR(10) NOT NULL,
  permit_type VARCHAR(200) NOT NULL,
  title VARCHAR(250) NOT NULL,
  permit_holder_name VARCHAR(200),
  client_company_name VARCHAR(200),
  description TEXT,
  eligibility_criteria TEXT,
  processing_time_days INTEGER CHECK (processing_time_days IS NULL OR processing_time_days >= 0),
  validity_months INTEGER CHECK (validity_months IS NULL OR validity_months >= 0),
  government_fee NUMERIC(14,2) CHECK (government_fee IS NULL OR government_fee >= 0),
  currency_code VARCHAR(10),
  worker_type VARCHAR(30) NOT NULL DEFAULT 'FOREIGN_WORKER'
    CHECK (worker_type IN ('LOCAL','FOREIGN_WORKER','EXPATRIATE','ALL_EMPLOYEES')),
  visibility VARCHAR(30) NOT NULL DEFAULT 'INTERNAL_STAFF'
    CHECK (visibility IN ('COMPLIANCE_ONLY','INTERNAL_STAFF','CLIENT_SHAREABLE')),
  source_url TEXT,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
    CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED')),
  last_reviewed_at DATE,
  next_review_at DATE,
  review_notes TEXT,
  information_status VARCHAR(20) NOT NULL DEFAULT 'CURRENT'
    CHECK (information_status IN ('CURRENT','REVIEW_DUE','OUTDATED','INCOMPLETE')),
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_work_permits_country ON work_permits (country_code);
CREATE INDEX IF NOT EXISTS idx_work_permits_status ON work_permits (status);
CREATE INDEX IF NOT EXISTS idx_work_permits_next_review ON work_permits (next_review_at);

CREATE TABLE IF NOT EXISTS work_permit_steps (
  step_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permit_id BIGINT NOT NULL REFERENCES work_permits(permit_id) ON DELETE CASCADE,
  process_type VARCHAR(20) NOT NULL DEFAULT 'NEW'
    CHECK (process_type IN ('NEW','RENEWAL','CANCELLATION')),
  step_number INTEGER NOT NULL CHECK (step_number >= 1),
  step_title VARCHAR(200) NOT NULL,
  step_detail TEXT,
  expected_timeline VARCHAR(120)
);
CREATE INDEX IF NOT EXISTS idx_work_permit_steps_permit
  ON work_permit_steps (permit_id, process_type);

CREATE TABLE IF NOT EXISTS permit_documents (
  document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permit_id BIGINT NOT NULL REFERENCES work_permits(permit_id) ON DELETE CASCADE,
  process_type VARCHAR(20) NOT NULL DEFAULT 'NEW'
    CHECK (process_type IN ('NEW','RENEWAL','CANCELLATION')),
  document_name VARCHAR(200) NOT NULL,
  is_mandatory BOOLEAN NOT NULL DEFAULT TRUE,
  notes VARCHAR(500),
  sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0)
);
CREATE INDEX IF NOT EXISTS idx_permit_documents_permit
  ON permit_documents (permit_id, process_type);

CREATE TABLE IF NOT EXISTS permit_source_documents (
  source_document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permit_id BIGINT NOT NULL REFERENCES work_permits(permit_id) ON DELETE CASCADE,
  original_file_name TEXT NOT NULL,
  stored_file_name TEXT NOT NULL,
  mime_type VARCHAR(150) NOT NULL,
  file_size BIGINT NOT NULL CHECK (file_size >= 0),
  file_hash VARCHAR(64),
  description TEXT,
  source_type VARCHAR(30) NOT NULL DEFAULT 'OFFICIAL_GUIDE'
    CHECK (source_type IN ('OFFICIAL_GUIDE','LEGISLATION','FORM','CIRCULAR','INTERNAL_NOTE','OTHER')),
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE','ARCHIVED')),
  uploaded_by VARCHAR(200),
  uploaded_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_permit_source_documents_permit
  ON permit_source_documents (permit_id, status);

CREATE TABLE IF NOT EXISTS permit_groups (
  group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_name VARCHAR(160) NOT NULL,
  description TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE','ARCHIVED')),
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_permit_groups_name_ci ON permit_groups (LOWER(group_name));
CREATE INDEX IF NOT EXISTS idx_permit_groups_status ON permit_groups (status, group_name);

CREATE TABLE IF NOT EXISTS permit_group_members (
  group_id BIGINT NOT NULL REFERENCES permit_groups(group_id) ON DELETE CASCADE,
  permit_id BIGINT NOT NULL REFERENCES work_permits(permit_id) ON DELETE CASCADE,
  added_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (group_id, permit_id)
);
CREATE INDEX IF NOT EXISTS idx_permit_group_members_permit
  ON permit_group_members (permit_id, group_id);
