-- Shared foundation (auth/users, countries, audit log) + Developer 1 —
-- Compliance Content Management. Mirrors server/database/schema.sql's
-- SQLite tables of the same name (docs/HIGH_LEVEL_DESIGN.md Section 12),
-- following the same conventions 001_initial_dev2_schema.sql already
-- established for this project: BIGINT identity PKs, TIMESTAMPTZ for
-- timestamps, VARCHAR + CHECK in place of SQLite's TEXT + CHECK "enums".

CREATE TABLE IF NOT EXISTS countries (
  country_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_code  VARCHAR(10) NOT NULL UNIQUE,
  country_name  VARCHAR(150) NOT NULL,
  region        VARCHAR(100),
  currency_code VARCHAR(10),
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
  user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name       VARCHAR(200) NOT NULL,
  email           VARCHAR(250) NOT NULL UNIQUE,
  password_hash   TEXT NOT NULL,
  role            VARCHAR(30) NOT NULL CHECK (role IN ('compliance','sales','customer_service','admin')),
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  failed_attempts INTEGER NOT NULL DEFAULT 0,
  last_login_at   TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS compliance_records (
  record_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id      BIGINT NOT NULL REFERENCES countries(country_id),
  category        VARCHAR(40) NOT NULL CHECK (category IN (
                    'LABOUR_LAW','SOCIAL_INSURANCE','WICA','TERMINATION',
                    'ANNUAL_LEAVE','SICK_LEAVE','MATERNITY_PATERNITY',
                    'WORKING_HOURS','STATUTORY_BENEFIT','GENERAL_GUIDELINE','OTHER')),
  title           VARCHAR(250) NOT NULL,
  summary         VARCHAR(500),
  full_text       TEXT,
  worker_type     VARCHAR(30) NOT NULL DEFAULT 'ALL_EMPLOYEES'
                    CHECK (worker_type IN ('LOCAL','FOREIGN_WORKER','EXPATRIATE','ALL_EMPLOYEES')),
  visibility      VARCHAR(30) NOT NULL DEFAULT 'INTERNAL_STAFF'
                    CHECK (visibility IN ('COMPLIANCE_ONLY','INTERNAL_STAFF','CLIENT_SHAREABLE')),
  effective_date  DATE,
  source_url      TEXT,
  version         INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
  status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED')),
  previous_status VARCHAR(20) CHECK (previous_status IN ('DRAFT','PUBLISHED')),
  archived_at     TIMESTAMPTZ,
  created_by      BIGINT REFERENCES users(user_id),
  updated_by      BIGINT REFERENCES users(user_id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_rec_country ON compliance_records(country_id);
CREATE INDEX IF NOT EXISTS idx_rec_category ON compliance_records(category);
CREATE INDEX IF NOT EXISTS idx_rec_status ON compliance_records(status);
CREATE INDEX IF NOT EXISTS idx_rec_worker ON compliance_records(worker_type);
CREATE INDEX IF NOT EXISTS idx_rec_visibility ON compliance_records(visibility);

-- Deliberately free-text rate/cap fields (not numeric) per HLD risk R5, same
-- rationale as the SQLite schema.
CREATE TABLE IF NOT EXISTS benefit_components (
  component_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_id         BIGINT NOT NULL REFERENCES compliance_records(record_id) ON DELETE CASCADE,
  component_name    VARCHAR(200) NOT NULL,
  worker_type       VARCHAR(30) NOT NULL DEFAULT 'ALL_EMPLOYEES'
                      CHECK (worker_type IN ('LOCAL','FOREIGN_WORKER','EXPATRIATE','ALL_EMPLOYEES')),
  employer_rate     VARCHAR(120),
  employee_rate     VARCHAR(120),
  cap_ceiling       VARCHAR(200),
  calculation_basis VARCHAR(200),
  notes             TEXT,
  sort_order        INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_comp_record ON benefit_components(record_id);

CREATE TABLE IF NOT EXISTS record_attachments (
  attachment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_id     BIGINT NOT NULL REFERENCES compliance_records(record_id) ON DELETE CASCADE,
  file_name     TEXT NOT NULL,
  file_path     TEXT NOT NULL,
  file_type     VARCHAR(150),
  uploaded_by   BIGINT REFERENCES users(user_id),
  uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_att_record ON record_attachments(record_id);

-- old_value/new_value stay TEXT (JSON.stringify'd by the app), not JSONB,
-- so the repository layer can use identical JSON.parse/stringify code on
-- both providers.
CREATE TABLE IF NOT EXISTS audit_logs (
  log_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT REFERENCES users(user_id),
  action       VARCHAR(20) NOT NULL CHECK (action IN ('create','update','archive','login','logout','publish')),
  admin_action VARCHAR(30) CHECK (admin_action IN ('RESTORE_ARCHIVED','PERMANENT_DELETE')),
  entity_type  VARCHAR(50) NOT NULL,
  entity_id    BIGINT,
  old_value    TEXT,
  new_value    TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_logs(entity_type, entity_id);
