-- Developer 3 — Review & Approval Workflow. Mirrors the SQLite tables of
-- the same name in server/database/schema.sql. target_id is polymorphic
-- across compliance_records and work_permits, so — same as the SQLite
-- schema — its relationship is validated in the service layer rather than
-- by a table foreign key.

CREATE TABLE IF NOT EXISTS review_requests (
  request_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_type     VARCHAR(30) NOT NULL CHECK (target_type IN ('compliance_record','work_permit')),
  target_id       BIGINT NOT NULL,
  title           VARCHAR(200) NOT NULL,
  description     TEXT,
  review_status   VARCHAR(30) NOT NULL DEFAULT 'PENDING'
                    CHECK (review_status IN ('PENDING','IN_REVIEW','APPROVED','CHANGES_REQUESTED','REJECTED','ARCHIVED')),
  previous_status VARCHAR(30) CHECK (previous_status IN ('PENDING','IN_REVIEW','APPROVED','CHANGES_REQUESTED','REJECTED')),
  archived_at     TIMESTAMPTZ,
  submitted_by    VARCHAR(200),
  reviewed_by     VARCHAR(200),
  submitted_at    TIMESTAMPTZ,
  reviewed_at     TIMESTAMPTZ,
  published_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL,
  updated_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_review_requests_status ON review_requests (review_status);
CREATE INDEX IF NOT EXISTS idx_review_requests_target ON review_requests (target_type, target_id);

CREATE TABLE IF NOT EXISTS review_comments (
  comment_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id  BIGINT NOT NULL REFERENCES review_requests(request_id),
  author_name VARCHAR(200) NOT NULL,
  comment     TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_review_comments_request ON review_comments (request_id);

CREATE TABLE IF NOT EXISTS notifications (
  notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id      BIGINT REFERENCES review_requests(request_id),
  recipient       VARCHAR(200) NOT NULL DEFAULT 'Compliance Team',
  message         TEXT NOT NULL,
  is_read         BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications (created_at DESC);

-- snapshot stays TEXT (JSON.stringify'd by reviewRepository.publish()), not
-- JSONB, for the same cross-provider-identical-code reason as audit_logs.
CREATE TABLE IF NOT EXISTS record_versions (
  version_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_type  VARCHAR(30) NOT NULL,
  target_id    BIGINT NOT NULL,
  version      INTEGER NOT NULL,
  snapshot     TEXT NOT NULL,
  published_at TIMESTAMPTZ NOT NULL,
  review_id    BIGINT NOT NULL REFERENCES review_requests(request_id),
  UNIQUE (target_type, target_id, version)
);
CREATE INDEX IF NOT EXISTS idx_record_versions_target ON record_versions (target_type, target_id);
