-- Developer 4 — Legal Updates / Newsletter Management. Mirrors the SQLite
-- tables of the same name in server/database/schema.sql. country stays
-- free text (no countries FK), and is_deleted is a soft delete, matching
-- the SQLite schema's own rationale for both.

CREATE TABLE IF NOT EXISTS newsletters (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title          VARCHAR(250) NOT NULL,
  country        VARCHAR(100) NOT NULL,
  source         VARCHAR(250),
  published_date DATE,
  status         VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','reviewed','archived')),
  notes          TEXT,
  file_name      TEXT,
  file_path      TEXT,
  is_deleted     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_newsletters_status ON newsletters (status);

CREATE TABLE IF NOT EXISTS detected_updates (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  newsletter_id          BIGINT NOT NULL REFERENCES newsletters(id) ON DELETE CASCADE,
  ai_summary             TEXT,
  ai_flagged             BOOLEAN NOT NULL DEFAULT FALSE,
  ai_flag_reason         TEXT,
  review_decision        VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (review_decision IN ('pending','confirmed','dismissed')),
  linked_compliance_area VARCHAR(250),
  reviewed_at            TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_detected_updates_newsletter ON detected_updates (newsletter_id);
