// Shared enumerations (docs/HIGH_LEVEL_DESIGN.md Section 12) — must stay in
// sync with client/src/utils/enums.js.

const WORKER_TYPES = ['LOCAL', 'FOREIGN_WORKER', 'EXPATRIATE', 'ALL_EMPLOYEES'];

const VISIBILITY_LEVELS = ['COMPLIANCE_ONLY', 'INTERNAL_STAFF', 'CLIENT_SHAREABLE'];

const CONTENT_STATUSES = ['DRAFT', 'PUBLISHED', 'ARCHIVED'];

const RECORD_CATEGORIES = [
  'LABOUR_LAW',
  'SOCIAL_INSURANCE',
  'WICA',
  'TERMINATION',
  'ANNUAL_LEAVE',
  'SICK_LEAVE',
  'MATERNITY_PATERNITY',
  'WORKING_HOURS',
  'STATUTORY_BENEFIT',
  'GENERAL_GUIDELINE',
  'OTHER',
];

module.exports = { WORKER_TYPES, VISIBILITY_LEVELS, CONTENT_STATUSES, RECORD_CATEGORIES };
